/***********************************************************************/
/*                                                                     */
/*  FILE        :cregdef.h                                             */
/*  DATE        :Thu, Feb 27, 2014                                     */
/*  DESCRIPTION :define the internal registers of MCU.                 */
/*  CPU GROUP   :80                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/*********************************************************************
 *  STARTUP for M32C/9X
 *  Copyright (C) 2004 (2010) Renesas Electronics Corporation.
 *  and Renesas Solutions Corporation. All rights reserved. 
 *
 *  cregdef.h : defined control register
 *
 *  note: Do not modify
 *
 * $Date: 2005/11/01 04:35:51 $
 * $Revision: 1.6 $
 *********************************************************************/

#pragma CREG	_flg_	flg
#pragma CREG	_isp_	isp
#pragma CREG	_sp_	sp
#pragma CREG	_sb_	sb
#pragma CREG	_fb_	fb
#pragma CREG	_intb_	intb
_UINT _flg_;
_UBYTE _far * _sb_;
_UBYTE _far * _fb_;
_UINT *_sp_;
_UINT *_isp_;
_UBYTE _far *_intb_;


