/***********************************************************************/
/*                                                                     */
/*  FILE        :heapdef.h                                             */
/*  DATE        :Thu, Feb 27, 2014                                     */
/*  DESCRIPTION :initialize the heap area.                             */
/*  CPU GROUP   :80                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : M32C/80,M16C/80,M16C/70
*
* File Name  : heapdef.h
*
* Abstract   : heap size definition
*
* History    : 1.90  (2010-03-01)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2004 (2010) Renesas Electronics Corporation.
* and Renesas Solutions Corporation. All rights reserved.
*
*********************************************************************/
#ifdef __HEAP__
extern	_UBYTE _far * _mnext; 
extern	_UDWORD _msize; 
//////////////////////////////////////////
// It's size of heap
// When you want to change size of heap, 
// please change this line.
// When you change this line,
// you must modify the value using hex character.

#ifndef __HEAPSIZE__
#define __HEAPSIZE__	0x300UL
#endif
extern _UBYTE heap_area[__HEAPSIZE__];
_inline void heap_init(void);
_inline void heap_init(void)
{
	_mnext = &heap_area[0];
	_msize = __HEAPSIZE__;
}

#endif
