/***********************************************************************/
/*                                                                     */
/*  FILE        :initsct.c                                             */
/*  DATE        :Thu, Feb 27, 2014                                     */
/*  DESCRIPTION :initialize each sections.                             */
/*  CPU GROUP   :80                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : M32C/80,M16C/80/70
*
* File Name  : initsct.c
*
* Abstract   : initialize each sections.
*
* History    : 1.70  (2009-12-08)
*            : 1.71  (2010-03-01)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2009 (2010) Renesas Electronics Corporation.
*  and Renesas Solutions Corporation. All rights reserved.
*
*********************************************************************/

#include "initsct.h"
void initsct(void);

void initsct(void)
{
	sclear("bss_SE","data","align");
	sclear("bss_SO","data","noalign");
	sclear("bss_NE","data","align");
	sclear("bss_NO","data","noalign");
	sclear("bss_FE","data","align");
	sclear("bss_FO","data","noalign");

	/* clear bss for NSD */
	sclear("bss_MON1_E","data","align");
	sclear("bss_MON2_E","data","align");
	sclear("bss_MON3_E","data","align");
	sclear("bss_MON4_E","data","align");
	sclear("bss_MON1_O","data","noalign");
	sclear("bss_MON2_O","data","noalign");
	sclear("bss_MON3_O","data","noalign");
	sclear("bss_MON4_O","data","noalign");

	// add new sections. refer to the above-mentioned.

	scopy("data_SE","data","align");
	scopy("data_SO","data","noalign");
	scopy("data_NE","data","align");
	scopy("data_NO","data","noalign");

	/* copy data section for NSD */
	scopy("data_MON1_E","data","align");
	scopy("data_MON2_E","data","align");
	scopy("data_MON3_E","data","align");
	scopy("data_MON4_E","data","align");
	scopy("data_MON1_O","data","noalign");
	scopy("data_MON2_O","data","noalign");
	scopy("data_MON3_O","data","noalign");
	scopy("data_MON4_O","data","noalign");
	scopy("data_FE","data","align");
	scopy("data_FO","data","noalign");

}
