/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.h                                            */
/*  DATE        :Thu, Feb 27, 2014                                     */
/*  DESCRIPTION :include some headder files.                           */
/*  CPU GROUP   :80                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/***********************************************************************
 *  startup for M32C/90,M32C/80,M16C/80,M16C/70
 *  Copyright (C) 2004 (2010) Renesas Electronics Corporation.
 *  and Renesas Solutions Corporation. All rights reserved.          
 *
 *  resetprg.h : include any headder files
 *
 *  Function: include any Headder files and prototype difinition
 *
 * $Date: 2005/11/25 10:26:31 $
 * $Revision: 1.9 $
 **********************************************************************/
///////////////////////////////////////////////
// include some header files.
// declare prototype difinition
//
#include "typedefine.h"
#include "heapdef.h"
#include "cregdef.h"
#include "stackdef.h"
#include "vector.h"

#define  DEF_SBREGISTER		_asm("	.glb	__SB__\n"\
				"__SB__	.equ	0400H")
