/***********************************************************************/
/*                                                                     */
/*  FILE        :stackdef.h                                            */
/*  DATE        :Thu, Feb 27, 2014                                     */
/*  DESCRIPTION :define the size of stack.                             */
/*  CPU GROUP   :80                                                    */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.18).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/

/**********************************************************************
 *  startup for M16C/M32C
 *  Copyright (C) 2004 (2010) Renesas Electronics Corporation.
 *  and Renesas Solutions Corporation. All rights reserved.                             *
 *  stackdef.h : stack size difinition
 *
 *  Function: define ustack size and istack size
 *
 * $Date: 2005/11/01 04:35:51 $
 * $Revision: 1.5 $
 *********************************************************************/
//////////////////////////////////////////////////////
// define the size of stack
// When you change the size of stack,
// modify these lines.
// specify stacksize using -D option.
//
#ifndef __STACKSIZE__
#pragma STACKSIZE	0x300
#else
#pragma STACKSIZE	__STACKSIZE__
#endif
#ifndef __ISTACKSIZE__
#pragma ISTACKSIZE	0x300
#else
#pragma ISTACKSIZE	__ISTACKSIZE__
#endif
extern _UINT _stack_top,_istack_top;

